config/routes.rb
Agenda::Application.routes.draw do
  resources :pessoas

end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  # GET /pessoas
  # GET /pessoas.xml
  def index
    @pessoas = Pessoa.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pessoas }
    end
  end

  # GET /pessoas/1
  # GET /pessoas/1.xml
  def show
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pessoa }
    end
  end

  # GET /pessoas/new
  # GET /pessoas/new.xml
  def new
    @pessoa = Pessoa.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pessoa }
    end
  end

  # GET /pessoas/1/edit
  def edit
    @pessoa = Pessoa.find(params[:id])
  end

  # POST /pessoas
  # POST /pessoas.xml
  def create
    @pessoa = Pessoa.new(params[:pessoa])

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to(@pessoa, :notice => 'Pessoa was successfully created.') }
        format.xml  { render :xml => @pessoa, :status => :created, :location => @pessoa }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pessoa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pessoas/1
  # PUT /pessoas/1.xml
  def update
    @pessoa = Pessoa.find(params[:id])

    respond_to do |format|
      if @pessoa.update_attributes(params[:pessoa])
        format.html { redirect_to(@pessoa, :notice => 'Pessoa was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pessoa.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.xml
  def destroy
    @pessoa = Pessoa.find(params[:id])
    @pessoa.destroy

    respond_to do |format|
      format.html { redirect_to(pessoas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agenda</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :data_de_nascimento %><br />
    <%= f.date_select :data_de_nascimento, :start_year => 1970 %>
  </div>
  <div class="field">
    <%= f.label :altura %><br />
    <%= f.text_field :altura %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Data de nascimento</th>
    <th>Altura</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pessoas.each do |pessoa| %>
  <tr>
    <td><%= pessoa.nome %></td>
    <td><%= pessoa.data_de_nascimento %></td>
    <td><%= pessoa.altura %></td>
    <td><%= link_to 'Show', pessoa %></td>
    <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
    <td><%= link_to 'Destroy', pessoa, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pessoa.nome %>
</p>

<p>
  <b>Data de nascimento:</b>
  <%= @pessoa.data_de_nascimento %>
</p>

<p>
  <b>Altura:</b>
  <%= @pessoa.altura %>
</p>


<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>